
   <h1>About Midwest Homebrewing and Winemaking Supplies</h1>
  
                    <div align="left">
                        The items below will explain a little about us and our philosophy. This is an 
                        exciting time for us, so be sure to bookmark our site so you can watch our 
                        new&nbsp;site grow and evolve. Plus it will allow you to check in on our great 
                        monthly specials.</div>
   
    <div align="left">
        <strong>WHO?</strong>Midwest is one of the largest retail home 
        brew&nbsp; and wine making supply shops in the United States. Our employees have 
        years of homebrewing and wine making experience from extract brewing to all 
        grain brewing. Our staff can also formulate beer recipes and wine recipes. We 
        can answer all your questions about home brewing and home wine making. Our 
        employees have make 1000&#39;s of batches of beer and wine!</div>
   
    <div align="left">
        <strong>WHAT?</strong>Our inventory is huge. Rarely will you find 
        that we are out of an homebrew or wine making product. Our malt extract, hops 
        and yeast arrive weekly, guaranteeing freshness. We are &quot;THE KING OF KITS&quot;. We 
        are constantly brewing and fine tuning our selection of homebrewing recipe kits. 
        Checkout all of our&nbsp;113 homebrewing<a href="http://www.midwestsupplies.com/products/recpkits.asp" 
         target="_blank">recipe kits</a> and&nbsp;132
         <a href="http://www.midwestsupplies.com/products/ProdByCat.aspx?Cat=120" 
            target="_blank">wine kits</a>. 
        Keep in touch with our web site and check out our recipes of the month and 
        seasonal recipe specials.</div>
    
    <div align="left">
        <strong>WHY?</strong> Why do we give out so many free homebrewing 
        and winemaking DVD&#39;s? Because it helps to see someone demonstrating beer and 
        winemaking techniques on video. This takes any guess work out of these 
        hobbies&nbsp;and will give you more consistent results. Intermediate to advanced 
        brewers will appreciate this video as well. We decided to make our beer recipe 
        kits available nationally because of our customers. They kept telling us how the 
        quality and selection of our recipe kits are better than any they had seen 
        locally and nationally. After checking out every single homebrewing web site on 
        the internet and getting a catalog from each outlet, we think they are right. We 
        are proud of our selection.</div>
   
    <div align="left">
        <strong>
        <a href="http://maps.google.com/maps?q=3440+Belt+Line+Blvd,+Minneapolis,+MN+55416&amp;hl=en" 
             target="_blank">WHERE?</a></strong>&nbsp; 
        Our store address is 3440 Belt Line Blvd., Minneapolis, MN 55416 / <a 
            href="http://maps.google.com/maps?q=3440+Belt+Line+Blvd,+Minneapolis,+MN+55416&amp;hl=en" 
            target="_blank">Click Here 
        for Directions and a Map</a><br />
        Phone - 1 (952) 925-9835<br />
        Toll Free - 1 (888) 449-BREW (2739)<br />
        Shipping Center - 1 (888) 449-2739<br />
        Fax - 1 (952) 925-9867</div>
    <div align="left">
        <b>Regular Store Hours: <br />
        </b>Monday-Friday 10 AM to 7 PM CST <br />
        Saturday 10 AM to 5 PM CST<br />
        Sunday 11 AM to 3 PM CST</div>
    <div align="left">
        &nbsp;<strong><a href="http://www.midwestsupplies.com/Ordering.asp" rel="nofollow" 
            target="_blank">WHEN?</a> </strong>Our 
        orders are shipped FedEx directly from our store on a daily basis. With our 
        FedEx tracking system we&#39;ll know exactly where your product is from the time it 
        leaves our store until it arrives at your home. <strong>We charge 
        you exactly what FedEx charges us. That saves you money! Some shops dramatically 
        inflate their prices and offer free shipping, while others set shipping rates 
        based on the dollar amount purchased. Either way you end up paying inflated 
        prices. Compare suppliers and save money with Midwest!</strong><b> </b>We 
        offer a 30 day money back guarantee.</div>