<?php
$blockReader = new Wdc_Cms_Block_Block();
?>

<div class="headerline-wrapper">

<div class="headerline-left">
<div class ="headerline-toplabel"><img src="<?php echo $this->getSkinUrl('images/labels/monthlyspotlight.gif'); ?>" />
</div>
<div class ="headerline-callout headerline-callout-top">
<p class="headline">Grape Harvest<br> Equipment</p>
<p class="headline-text">
In stock and <br/>ready to ship!<br/>
<a href="" onmouseover="toggleVisibility(true,document.getElementById('block8'))" onmouseout="toggleVisibility(false,document.getElementById('block8'))">Need more info?</a>
<div id="block8" class="block-float">
<h2 class="blockheader"><?php echo $blockReader->getTitle(8) ?></h2>
<p class="blocktext">
<?php echo $blockReader->getContent(8) ?>
</p>

</div>
</p>
</div>
<div class ="headerline-callout headerline-callout-bot">
<p class="headline">Brew a classic Autumn Beer recipe</p>
<p class="headline-text">
Check out our <br>autumn ales<br>
<a href="#" onmouseover="toggleVisibility(true,document.getElementById('block7'))" onmouseout="toggleVisibility(false,document.getElementById('block7'))">Need more<br/> info?</a>
<div id="block7" class="block-float">
<h2 class="blockheader"><?php echo $blockReader->getTitle(7) ?></h2>
<p class="blocktext">
<?php echo $blockReader->getContent(7) ?>
</p>
</div>
</p>
</div>
</div>

<div class="headerline-main">
<img src="<?php echo $this->getSkinUrl('images/headliner/header0709a.jpg'); ?>" />
<div class="lenny">DO WANT <br>SAVE MONEY?</div>
</div>
</div>
<div class="midline-wrapper">
<a href="#" onclick="toggleVisibility(true,document.getElementById('info-block'))">
<img src="<?php echo $this->getSkinUrl('images/headliner/sep_image.gif'); ?>" />
</a>
</div>


<div id="info-block" class="block-text-info">
<a href="#" onclick="toggleVisibility(false,document.getElementById('info-block'))">X CLOSE</a>
{{block type="core/template" template="Wdc/frontpage/bottomer.phtml"}}
</div>







