<?php

//$_product    = $this->getProduct();
$obj = new Mage_Catalog_Block_Product_View_Attributes();
$_product = $obj->setProduct(167);
//$this->_product = $_product;

$att = new Mage_Catalog_Block_Product_View_Type_Configurable();
$helper = new Mage_Core_Helper_Data();


//$_product    = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($att->getAllowAttributes());


?>
   