<?php
/**
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>
<div id="footer">
  <div class="inner">
    <div class="right">
    <ul id="footer-links">
       <li><a href="home.html">home</a></li>
       <li><a href="about.html">about</a></li>
       <li><a href="story.html">our story</a></li>
       <li><a href="eco-friendly">eco-friendly</a></li>
       <li><a href="testimonials.html">testimonials</a></li>
       <li><a href="tips.html">healthy home tips</a></li>
       <li><a href="faq.html">faq</a></li>
       <li><a href="press.html">press</a></li>
       <li><a href="contact.php">contact</a></li>
    </ul><!-- /footer-links-->
    
    <ul id="second-footer-links">
      <li><a href="#">Shipping &amp; Return Info</a></li>
      <li><a href="#">Security &amp; Privacy Policy</a></li>
      <li><a href="#">Terms &amp; Conditions</a></li>
    </ul><!--/second-footer-links-->
    </div>
    <p>Copyright &copy; 2010 Dr. Doormat - All Rights Reserved</p>
  </div><!-- /inner-->
</div><!-- /#footer-->