<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<?php echo $this->getChildHtml('head') ?>
 <script src="http://github.com/mathiasbynens/Simplest-jQuery-Slideshow/raw/master/jquery.slideshow.js"></script> 
</head>

<!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->

  <div id="container" class="shop-page">
    <div class="main-wrap">
   <?php echo $this->getChildHtml('global_notices') ?>
   <?php echo $this->getChildHtml('header') ?>
    <div id="main" >
      <div class="heading">
        <div class="inner">
         <h2>CHOOSE YOUR MAT</h2> 
        </div><!-- /inner-->
      </div><!--/heading-->
      <div class="inner story" >
          <script type="text/javascript">
            jQuery(function() {
             jQuery('.slideshow').slideshow({ timeout: 3000, speed: 200 });
            });
          </script>
          
          <div id="product-sizes">
            <h3>DR. Doormat available sizes</h3>
            <ul>
              <li>
                <h2>apartment size</h2>
                <p><strong>18" x 24" x 7/16"</strong></p>
                <p><span>$24.99</span> + Shipping</p><br />
                <p>Ideal for smaller living spaces including townhouse 
                living, condo, dorm room, office, the beach house or a flat.  
                The perfect mat for your pet’s food dishes, a boat, small 
                pet crate, the kitchen sink or the baby nursery.  Wherever you 
                use Dr. Doormat, we’re sure you’ll find the right color for the 
                precise location in your home.</p>
              </li>
              
              <li>
                <h2>house size</h2>
                <p><strong>24" x 36" x 7/16""</strong></p>
                <p><span>$34.99</span> + Shipping</p><br />
                <p>More traffic requires a bigger mat.  Dr. Doormat blends  
                sophisticated elegance and functionality while handling 
                the crowds at the front entrance, back door, mud room, kitchen 
                door, garage entrance and doggie door.  Place two mats end to 
                end to create an even larger walk off area for a doggie entrance or
                 cat litter box.  Imagine all the possibilities including the 
                kitchen sink.</p>
              </li>
            </ul>
            <div class="clear"></div>
          </div><!-- /product-sizes-->
          
        <div class="clear"></div>
        <?php echo $this->getChildHtml('global_messages') ?>    
        <?php echo $this->getChildHtml('content') ?>  
        <div id="product-slideshow">
          <ul class="slideshow"> 
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s1.jpg') ?>" alt=""></li> 
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s2.jpg') ?>" alt=""></li>
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s3.jpg') ?>" alt=""></li>
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s4.jpg') ?>" alt=""></li>
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s6.jpg') ?>" alt=""></li>
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s8.jpg') ?>" alt=""></li>
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s9.jpg') ?>" alt=""></li>
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s11.jpg') ?>" alt=""></li>
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s11.jpg') ?>" alt=""></li>
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s12.jpg') ?>" alt=""></li>
             <li><img src="<?php echo $this->getSkinUrl('images/slide/s13.jpg') ?>" alt=""></li>                    
            </ul>
             <p style="margin: 470px 0px 10px; font-size: 12px;">
               <strong>Beyond the Front Door</strong><br/><br />
               Place Dr. Doormat at key locations throughout the home where bacteria, dust and microbes  gather such as underneath the kitchen sink, under pet dishes, underneath your cat litter box or at the entrance of your doggie door.   
<br><br>
               Replacing your dog’s pillow with Dr. Doormat helps eliminate dog odors and the spread of pet dander.    
<br><br>
               Placing a mat outside the nursery or playroom offers extra protection since babies and toddlers are the most vulnerable to household dust.   The antimicrobial formula can’t penetrate the skin and is safe for all family members.  
<br><br>
               For allergy and asthma sufferers, placing Dr. Doormat outside the bedroom or on the floor by the bed offers an additional line of defense against dust mites and other allergens.   Throughout your home it’s nice to know that Dr. Doormat is working for you 24/7.
            <br /><br /></p>
        </div><!-- /product-slideshow-->
        
        <br /><br />
      <div class="clear"></div>
      <p>Once you complete the ordering process, we will only charge your credit card a $1 deposit to ensure your reserved mat.  When your order is ready to be shipped, you will be notified and then charged the full amount minus the deposit.  </p>
      </div><!--/.inner-->
    </div><!-- /#main-->  
    <div class="clear"></div>
    <div class="push"></div>
    </div><!-- /main-wrap-->
    <?php echo $this->getChildHtml('footer') ?>
    
  </div> <!--! end of #container -->

</body>
</html>
