<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<!--[if lt IE 7 ]> <body class="ie6"> <![endif]-->
<!--[if IE 7 ]>    <body class="ie7"> <![endif]-->
<!--[if IE 8 ]>    <body class="ie8"> <![endif]-->
<!--[if IE 9 ]>    <body class="ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <body> <!--<![endif]-->

  <div id="container" class="shop-page">
    <div class="main-wrap">
   <?php echo $this->getChildHtml('global_notices') ?>
   <?php echo $this->getChildHtml('header') ?>
    <div id="main" >
      <div class="heading">
        <div class="inner">
         <h2>Products</h2> 
        </div><!-- /inner-->
      </div><!--/heading-->
      <div class="inner story" >
        <?php echo $this->getChildHtml('global_messages') ?>
        <?php echo $this->getChildHtml('content') ?>  
      <div class="clear"></div>
      </div><!--/.inner-->
    </div><!-- /#main-->  
    <div class="clear"></div>
    <div class="push"></div>
    </div><!-- /main-wrap-->
    <?php echo $this->getChildHtml('footer') ?>
    
  </div> <!--! end of #container -->

</body>
</html>
